include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: false
    avoid_redundant_argument_values: false
